import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { bindings } from "../bindings.server";
const clean=(x:any)=>JSON.parse(JSON.stringify(x));
const rental=z.object({customerId:z.number().nullable(),vehicleId:z.number().nullable(),serviceId:z.number().nullable(),startAt:z.string(),endAt:z.string(),quantity:z.number().positive(),unitPrice:z.number().nonnegative(),discount:z.number().nonnegative(),vatRate:z.number().nonnegative(),deposit:z.number().nonnegative(),paymentMethod:z.string().nullable(),notes:z.string().nullable()});
export const getDashboard=createServerFn({method:"GET"}).handler(async()=>{const {DB}=bindings();if(!DB)return {summary:{revenue:0,expenses:0,vat:0,outstanding:0,bookings:0},rentals:[],expenses:[],vehicles:[],customers:[],services:[]};const [s,r,e,v,c,sv]=await Promise.all([DB.prepare("SELECT COALESCE(SUM(total),0) revenue,COALESCE(SUM(vat_amount),0) vat,COALESCE(SUM(CASE WHEN payment_status!='paid' THEN total ELSE 0 END),0) outstanding,COUNT(*) bookings FROM rentals").first<any>(),DB.prepare("SELECT r.*,c.name customer_name,v.name vehicle_name,s.name service_name FROM rentals r LEFT JOIN customers c ON c.id=r.customer_id LEFT JOIN vehicles v ON v.id=r.vehicle_id LEFT JOIN services s ON s.id=r.service_id ORDER BY r.id DESC LIMIT 200").all(),DB.prepare("SELECT e.*,v.name vehicle_name FROM expenses e LEFT JOIN vehicles v ON v.id=e.vehicle_id ORDER BY e.id DESC LIMIT 200").all(),DB.prepare("SELECT * FROM vehicles ORDER BY id DESC").all(),DB.prepare("SELECT * FROM customers ORDER BY id DESC").all(),DB.prepare("SELECT * FROM services ORDER BY id DESC").all()]);const ex=await DB.prepare("SELECT COALESCE(SUM(amount),0) expenses FROM expenses").first<any>();return clean({summary:{revenue:s?.revenue??0,expenses:ex?.expenses??0,vat:s?.vat??0,outstanding:s?.outstanding??0,bookings:s?.bookings??0},rentals:r.results,expenses:e.results,vehicles:v.results,customers:c.results,services:sv.results});});
export const createRental=createServerFn({method:"POST"}).inputValidator(rental).handler(async({data})=>{const {DB}=bindings();if(!DB)throw new Error("Database unavailable");const subtotal=Math.round(data.quantity*data.unitPrice*100)/100;const taxable=Math.max(0,subtotal-data.discount);const vat=Math.round(taxable*data.vatRate)/100;const total=Math.round((taxable+vat)*100)/100;const invoice="RNT-"+Date.now();const row=await DB.prepare("INSERT INTO rentals (invoice_no,customer_id,vehicle_id,service_id,start_at,end_at,quantity,unit_price,subtotal,discount,vat_rate,vat_amount,total,deposit,payment_status,payment_method,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id,invoice_no,total").bind(invoice,data.customerId,data.vehicleId,data.serviceId,data.startAt,data.endAt,data.quantity,data.unitPrice,subtotal,data.discount,data.vatRate,vat,total,data.deposit,data.paymentMethod?"paid":"unpaid",data.paymentMethod,data.notes).first();return clean(row);});
export const createExpense=createServerFn({method:"POST"}).inputValidator(z.object({expenseDate:z.string(),category:z.string(),description:z.string().min(1),amount:z.number().nonnegative(),vatAmount:z.number().nonnegative(),paymentMethod:z.string().nullable(),vehicleId:z.number().nullable()})).handler(async({data})=>{const {DB}=bindings();if(!DB)throw new Error("Database unavailable");const row=await DB.prepare("INSERT INTO expenses (expense_date,category,description,amount,vat_amount,payment_method,vehicle_id) VALUES (?,?,?,?,?,?,?) RETURNING *").bind(data.expenseDate,data.category,data.description,data.amount,data.vatAmount,data.paymentMethod,data.vehicleId).first();return clean(row);});
export const createEntity=createServerFn({method:"POST"}).inputValidator(z.object({kind:z.enum(["vehicle","customer","service"]),name:z.string().min(1),category:z.string(),price:z.number().nonnegative(),rate:z.number().nonnegative(),phone:z.string().nullable(),email:z.string().nullable(),nationality:z.string().nullable(),idReference:z.string().nullable()})).handler(async({data})=>{const {DB}=bindings();if(!DB)throw new Error("Database unavailable");if(data.kind==="vehicle")await DB.prepare("INSERT INTO vehicles (name,category,rate_per_hour) VALUES (?,?,?)").bind(data.name,data.category,data.rate).run();else if(data.kind==="customer")await DB.prepare("INSERT INTO customers (name,phone,email,nationality,id_reference) VALUES (?,?,?,?,?)").bind(data.name,data.phone,data.email,data.nationality,data.idReference).run();else await DB.prepare("INSERT INTO services (name,category,price) VALUES (?,?,?)").bind(data.name,data.category,data.price).run();return {ok:true};});
