(function(){
var K="quad_rental_standalone_v1",S=JSON.parse(localStorage.getItem(K)||"null")||{vehicles:[],customers:[],services:[],bookings:[],expenses:[]},tab="Overview",modal="";
function save(){localStorage.setItem(K,JSON.stringify(S));render()}
function money(n){return "AED "+Number(n||0).toLocaleString("en-AE",{minimumFractionDigits:2,maximumFractionDigits:2})}
function total(k){return S[k].reduce(function(a,x){return a+Number(x.amount||x.total||0)},0)}
function nav(){return ["Overview","Bookings","Vehicles","Customers","Services","Expenses","Reports"].map(function(x){return '<button class="'+(tab==x?"active":"")+'" onclick="go(\''+x+'\')">'+x+"</button>"}).join("")}
function shell(x){return '<div class="app"><aside class="side"><div class="brand">QUAD <i>RENTAL</i><br>UAE DESK</div><div class="nav">'+nav()+'</div></aside><main class="main"><div class="mobile">'+nav()+'</div>'+x+'</main>'+(modal?modalHtml():"")+"</div>"}
function header(a,b,c){return '<div class="top"><div><h1>'+a+'</h1><div class="muted">'+b+"</div></div>"+(c||"")+"</div>"}
function table(rows,cols){if(!rows.length)return '<div class="card empty">No records yet.</div>';return '<div class="tablebox"><table class="table"><thead><tr>'+cols.map(function(c){return "<th>"+c+"</th>"}).join("")+'</tr></thead><tbody>'+rows.slice().reverse().map(function(r){return "<tr>"+cols.map(function(c){var v=r[c];if(["amount","total","price","rate"].indexOf(c)>=0)v=money(v);return "<td>"+(v==null?"":v)+"</td>"}).join("")+"</tr>"}).join("")+"</tbody></table></div>"}
function overview(){var rev=total("bookings"),ex=total("expenses"),out=S.bookings.filter(function(x){return x.paymentStatus!="paid"}).reduce(function(a,x){return a+Number(x.total||0)},0);return header("Overview","Rental operations and cashflow.",'<button class="btn primary" style="width:auto" onclick="openm(\'booking\')">+ New booking</button>')+'<div class="grid"><div class="card">Revenue<div class="metric accent">'+money(rev)+'</div></div><div class="card">Expenses<div class="metric">'+money(ex)+'</div></div><div class="card">Net result<div class="metric accent">'+money(rev-ex)+'</div></div><div class="card">Outstanding<div class="metric">'+money(out)+'</div></div></div><div class="section"><h2>Recent bookings</h2>'+table(S.bookings,["invoice","customer","vehicle","total","paymentStatus"])+"</div>"}
function listing(k,title,desc,cols){return header(title,desc,'<button class="btn primary" style="width:auto" onclick="openm(\''+k+'\')">+ Add</button>')+'<div class="section">'+table(S[k],cols)+"</div>"}
function reports(){return header("Reports","Export and backup your rental data.")+'<div class="card"><h3>Exports</h3><div class="actions"><button class="btn" onclick="csv(\'bookings\')">Bookings CSV</button><button class="btn" onclick="csv(\'expenses\')">Expenses CSV</button><button class="btn" onclick="csv(\'vehicles\')">Vehicles CSV</button><button class="btn" onclick="csv(\'customers\')">Customers CSV</button><button class="btn" onclick="csv(\'services\')">Services CSV</button><button class="btn primary" onclick="backup()">Full JSON backup</button></div></div><div class="section card">Data is stored locally in this browser for this standalone version. Use the JSON backup regularly.</div>'}
function form(fields){return '<div class="form">'+fields.map(function(f){return '<div class="field '+(f[0]=="description"?"full":"")+'"><label>'+f[1]+'</label><input id="f_'+f[0]+'" type="'+(f[2]||"text")+'"></div>'}).join("")+"</div>"}
function modalHtml(){var title="",body="";if(modal=="booking"){title="New booking";body=form([["customer","Customer"],["vehicle","Vehicle"],["service","Service"],["qty","Hours / quantity","number"],["unit","Unit price AED","number"],["discount","Discount AED","number"],["vat","VAT %","number"],["deposit","Deposit AED","number"],["method","Payment method"],["paymentStatus","Payment status"],["start","Start","datetime-local"],["end","End","datetime-local"]])}else if(modal=="vehicles"){title="Add vehicle";body=form([["name","Vehicle name"],["category","Category"],["rate","Hourly rate AED","number"],["status","Status"]])}else if(modal=="customers"){title="Add customer";body=form([["name","Name"],["phone","Phone"],["email","Email"],["nationality","Nationality"],["idref","ID / passport reference"]])}else if(modal=="services"){title="Add service";body=form([["name","Service name"],["category","Category"],["price","Price AED","number"],["vat","VAT %","number"]])}else{title="Add expense";body=form([["date","Date","date"],["category","Category"],["description","Description"],["amount","Amount AED","number"],["vat","VAT amount AED","number"],["method","Payment method"]])}return '<div class="modal"><div class="modalbox"><div class="top"><b>'+title+'</b><button class="btn" style="width:auto" onclick="closem()">×</button></div>'+body+'<div class="actions" style="margin-top:16px"><button class="btn" style="width:auto" onclick="closem()">Cancel</button><button class="btn primary" style="width:auto" onclick="submit()">Save</button></div></div></div>'}
function val(x){var n=document.getElementById("f_"+x);return n?n.value:""}
window.go=function(x){tab=x;modal="";render()};window.openm=function(x){modal=x;render()};window.closem=function(){modal="";render()};
window.submit=function(){if(modal=="booking"){var q=+val("qty")||1,u=+val("unit")||0,d=+val("discount")||0,v=+val("vat")||5,tax=Math.max(0,q*u-d),va=tax*v/100;S.bookings.push({invoice:"RNT-"+Date.now(),customer:val("customer"),vehicle:val("vehicle"),service:val("service"),quantity:q,unit:u,total:tax+va,vatAmount:va,deposit:+val("deposit")||0,paymentStatus:val("paymentStatus")||"unpaid",method:val("method"),start:val("start"),end:val("end")})}else if(modal=="vehicles")S.vehicles.push({name:val("name"),category:val("category")||"Quad",rate:+val("rate")||0,status:val("status")||"available"});else if(modal=="customers")S.customers.push({name:val("name"),phone:val("phone"),email:val("email"),nationality:val("nationality"),idref:val("idref")});else if(modal=="services")S.services.push({name:val("name"),category:val("category")||"Other",price:+val("price")||0,vat:+val("vat")||5,active:true});else S.expenses.push({date:val("date"),category:val("category"),description:val("description"),amount:+val("amount")||0,vat:+val("vat")||0,method:val("method")});modal="";save()};
window.csv=function(k){var rows=S[k];if(!rows.length)return alert("No data.");var keys=Object.keys(rows[0]),txt=keys.join(",")+"\n"+rows.map(function(r){return keys.map(function(x){return '"'+String(r[x]||"").replace(/"/g,'""')+'"'}).join(",")}).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([txt],{type:"text/csv"}));a.download=k+".csv";a.click()};
window.backup=function(){var a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:"application/json"}));a.download="quad-rental-backup.json";a.click()};
function render(){var c=tab=="Overview"?overview():tab=="Bookings"?listing("bookings","Bookings","Rental invoices and payments.",["invoice","customer","vehicle","service","total","paymentStatus"]):tab=="Vehicles"?listing("vehicles","Vehicles","Quad and buggy fleet.",["name","category","rate","status"]):tab=="Customers"?listing("customers","Customers","Customer records.",["name","phone","nationality","email"]):tab=="Services"?listing("services","Services","Rental and other services.",["name","category","price","vat","active"]):tab=="Expenses"?listing("expenses","Expenses","Operating costs.",["date","category","description","amount","method"]):reports();document.getElementById("app").innerHTML=shell(c)}
render();
})();